Features/api
Haulmont/jmix-awsqueue pull request #1
Opened 2021-06-02 15:42 UTC by Vi3arD

added new api features (send message, subscribe)
added integration with yandex queues
modules were refactored and renamed

2021-06-02 16:09 UTC, AndreiDenisenko requested changes

2021-06-02 16:09 UTC, AndreiDenisenko commented on README.md
> +jmix.sqs.yandex.endpoint-configuration = https://message-queue.api.cloud.yandex.net
У Яндекса может быть другой endpoint configuration?

2021-06-02 16:09 UTC, AndreiDenisenko commented on README.md
> +implementation 'io.jmix.awsqueue:jmix-sqs-ui-starter'
Переименовываем группу в `io.jmix.simplequeue`
и стартер: `jmix-simplequeue-ui-starter`

2021-06-02 16:09 UTC, AndreiDenisenko commented on README.md
>  implementation 'io.jmix.awsqueue:jmix-awsqueue-starter'
`jmix-simplequeue-aws-starter`

2021-06-02 16:09 UTC, AndreiDenisenko commented on README.md
> +implementation 'io.jmix.awsqueue:jmix-yandexqueue-starter'
`jmix-simplequeue-yandex-starter`

2021-06-02 16:09 UTC, AndreiDenisenko commented on README.md
> +jmix.sqs.yandex.endpoint-configuration = https://message-queue.api.cloud.yandex.net
префикс пропертей `jmix.simplequeue.`

2021-06-02 16:09 UTC, AndreiDenisenko commented on README.md
> +jmix.sqs.yandex.queue-prefix = jmixqueues
Зачем мы разделяем `queue-prefix` по платформам?

2021-06-02 16:09 UTC, AndreiDenisenko commented on README.md
> +jmix.sqs.listener.thread-pool-core-size = 5
тоже самое про префикс параметров

2021-06-02 16:09 UTC, AndreiDenisenko commented on settings.gradle
> +include 'simple-queue-ui-starter'
`simplequeue` одним словом

2021-06-02 16:09 UTC, AndreiDenisenko commented on settings.gradle
>  rootProject.name = 'jmix-awsqueue'
поправить имя проекта

2021-06-02 16:09 UTC, AndreiDenisenko commented on simple-queue-api/src/main/java/io/jmix/simplequeue/impl/QueueManagerImpl.java
> +        });
Зачем так? Сначала computeIfAbsent создает список. Потом просто добавляешь в него lambdaHandler без условий.

2021-06-02 16:09 UTC, AndreiDenisenko commented on simple-queue-api/src/main/java/io/jmix/simplequeue/impl/QueueManagerImpl.java
> +        });
По неймингу `queuesHandlers`: обычно только второе слово во множественном числе пишется

2021-06-02 16:09 UTC, AndreiDenisenko commented on simple-queue-api/src/main/java/io/jmix/simplequeue/impl/QueueManagerImpl.java
> +            log.info(e.getMessage());
какая-то странная обработка ошибок с логированием в info

2021-06-02 16:09 UTC, AndreiDenisenko commented on simple-queue-api/src/main/java/io/jmix/simplequeue/api/QueueProperties.java
> +public interface QueueProperties {
зачем нам нужен этот интерфейс?

2021-06-02 16:15 UTC, Vi3arD commented on README.md
> +jmix.sqs.yandex.endpoint-configuration = https://message-queue.api.cloud.yandex.net
В теории да

2021-06-02 16:18 UTC, Vi3arD commented on README.md
> +jmix.sqs.yandex.queue-prefix = jmixqueues
потому что для каждой платформы идет свой QueueProperties класс в нем по @ConfigurationProperties(prefix = "jmix.sqs.yandex") такой аннотации получаются все аннотации с префиксом, что бы избавиться от разделения для queue-prefix нужен будет общий  QueueProperties, делать его?

2021-06-02 16:20 UTC, Vi3arD commented on simple-queue-api/src/main/java/io/jmix/simplequeue/impl/QueueManagerImpl.java
> +        });
по первому вопросу: а если у нас будет 2 листенера для одной очереди, то второй не добавится

2021-06-02 16:22 UTC, Vi3arD commented on simple-queue-api/src/main/java/io/jmix/simplequeue/api/QueueProperties.java
> +public interface QueueProperties {
ну чтобы через DI подставляешь параметры от очереди которая в данный момент подключена

2021-06-03 09:14 UTC, AndreiDenisenko commented on README.md
> +jmix.simplequeue.queue.prefix = jmixqueues
Кажется тут нарушена логика повествования и надо писать тогда `prefix`, а не `tag`

2021-06-03 11:39 UTC, AndreiDenisenko approved these changes

2021-06-03 14:15 UTC, merged